#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALF.UI.EduUI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eduData2015DB")]
	public partial class EduDataLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EduDataLINQDataContext() : 
				base(global::ALF.UI.Properties.Settings.Default.eduData2015DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EduDataLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduDataLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduDataLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduDataLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<return_getRegionTreeNodeList> return_getRegionTreeNodeLists
		{
			get
			{
				return this.GetTable<return_getRegionTreeNodeList>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.code_getRegionTreeNodeList")]
		public ISingleResult<return_getRegionTreeNodeList> code_getRegionTreeNodeList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> appType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string node1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string node2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string node3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string node4, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isShowOptionAll, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> recordYear)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), appType, node1, node2, node3, node4, isShowOptionAll, recordYear);
			return ((ISingleResult<return_getRegionTreeNodeList>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.return_getRegionTreeNodeList")]
	public partial class return_getRegionTreeNodeList
	{
		
		private string _nodeName;
		
		private string _nodeNo;
		
		private int _nodeLevel;
		
		private string _nodeOrganizationType;
		
		private int _nodeIsImmediacy;
		
		private int _nodeIsNation;
		
		private string _node1;
		
		private int _node1Level;
		
		private string _node2;
		
		private int _node2Level;
		
		private string _node3;
		
		private int _node3Level;
		
		private string _node4;
		
		private int _node4Level;
		
		private string _node5;
		
		private int _node5Level;
		
		public return_getRegionTreeNodeList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nodeName
		{
			get
			{
				return this._nodeName;
			}
			set
			{
				if ((this._nodeName != value))
				{
					this._nodeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nodeNo
		{
			get
			{
				return this._nodeNo;
			}
			set
			{
				if ((this._nodeNo != value))
				{
					this._nodeNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeLevel", DbType="Int NOT NULL")]
		public int nodeLevel
		{
			get
			{
				return this._nodeLevel;
			}
			set
			{
				if ((this._nodeLevel != value))
				{
					this._nodeLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeOrganizationType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nodeOrganizationType
		{
			get
			{
				return this._nodeOrganizationType;
			}
			set
			{
				if ((this._nodeOrganizationType != value))
				{
					this._nodeOrganizationType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeIsImmediacy", DbType="Int NOT NULL")]
		public int nodeIsImmediacy
		{
			get
			{
				return this._nodeIsImmediacy;
			}
			set
			{
				if ((this._nodeIsImmediacy != value))
				{
					this._nodeIsImmediacy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeIsNation", DbType="Int NOT NULL")]
		public int nodeIsNation
		{
			get
			{
				return this._nodeIsNation;
			}
			set
			{
				if ((this._nodeIsNation != value))
				{
					this._nodeIsNation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string node1
		{
			get
			{
				return this._node1;
			}
			set
			{
				if ((this._node1 != value))
				{
					this._node1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node1Level", DbType="Int NOT NULL")]
		public int node1Level
		{
			get
			{
				return this._node1Level;
			}
			set
			{
				if ((this._node1Level != value))
				{
					this._node1Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string node2
		{
			get
			{
				return this._node2;
			}
			set
			{
				if ((this._node2 != value))
				{
					this._node2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node2Level", DbType="Int NOT NULL")]
		public int node2Level
		{
			get
			{
				return this._node2Level;
			}
			set
			{
				if ((this._node2Level != value))
				{
					this._node2Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node3", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string node3
		{
			get
			{
				return this._node3;
			}
			set
			{
				if ((this._node3 != value))
				{
					this._node3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node3Level", DbType="Int NOT NULL")]
		public int node3Level
		{
			get
			{
				return this._node3Level;
			}
			set
			{
				if ((this._node3Level != value))
				{
					this._node3Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node4", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string node4
		{
			get
			{
				return this._node4;
			}
			set
			{
				if ((this._node4 != value))
				{
					this._node4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node4Level", DbType="Int NOT NULL")]
		public int node4Level
		{
			get
			{
				return this._node4Level;
			}
			set
			{
				if ((this._node4Level != value))
				{
					this._node4Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node5", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string node5
		{
			get
			{
				return this._node5;
			}
			set
			{
				if ((this._node5 != value))
				{
					this._node5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_node5Level", DbType="Int NOT NULL")]
		public int node5Level
		{
			get
			{
				return this._node5Level;
			}
			set
			{
				if ((this._node5Level != value))
				{
					this._node5Level = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
